name: "Build and Push"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'us-east-1'
      CLUSTER_NAME: 'projeto-fiap'
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build jar using Maven
      run: mvn package -Dmaven.test.skip
            
    - name: Build Docker Image and push to AWS ECR
      uses: kciter/aws-ecr-action@v4
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: projeto-fiap
        region: us-east-1
        create_repo: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Infrastructure Deploy Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: refs/heads/main
          workflow: terraform-apply.yml
          token: ${{ secrets.PAT }}  # Personal Access Token with repo scope
          repo: richard-cardosodev/projeto-fiap-iac-infra
          #inputs: '{"message": "Triggered from application deployment workflow"}'
