name: "Build and Push"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'us-east-1'
      CLUSTER_NAME: 'projeto-fiap'
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

      # Setup Maven and JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Folder content debug
      run: ls -l

    - name: Run basic tests
      run: mvn test

    - name: Runs the database and application
      run: |
        docker build . -t projeto-fiap-produto
        cd ./src/test/resources/deploy
        ls -l
        sed -i 's/DB_PASSWORD_PLACEHOLDER/${{ secrets.PROJETOFIAP_DB_PASSWORD }}/g' docker-compose.yml
        docker-compose up -d

    - name: Wait for Container to be Live and Monitor Containers
      run: |
        timeout=300
        elapsed=0
        echo "Waiting for container to be live..."
        while ! curl --head --fail http://localhost:8080/produto/liveness; do
          if [ $elapsed -ge $timeout ]; then
            echo "Timed out waiting for container to be live."
            exit 1
          fi
          printf '.'
        
          # Print the current status of Docker containers
          echo "======================================================"
          echo "Current time: $(date)"
          docker ps
          echo "======================================================"
          docker logs --tail 50 $(docker ps --filter name=db -q)
          docker logs --tail 50 $(docker ps --filter name=projeto-fiap-produto -q)
          echo "======================================================"
        
          sleep 10
          elapsed=$((elapsed + 10))
        done
        echo "Container is live!"

    - name: Run BDD tests
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean verify sonar:sonar -P bdd

    - name: Check for coverage report existence
      run: |
        ls -l target/site/jacoco/jacoco.xml

    - name: Check for BDD tests failures
      run: |
        if grep -q '<error message=' target/surefire-reports/*.xml; then
          echo "Falha nos testes BDD"
          exit 1
        fi

    - name: Build jar using Maven
      run: mvn package -Dmaven.test.skip
            
    - name: Build Docker Image and push to AWS ECR
      uses: kciter/aws-ecr-action@v4
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: projeto-fiap-produto
        region: us-east-1
        create_repo: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Infrastructure Deploy Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: refs/heads/main
          workflow: terraform-apply.yml
          token: ${{ secrets.PAT }}  # Personal Access Token with repo scope
          repo: richard-cardosodev/projeto-fiap-iac-infra
          #inputs: '{"message": "Triggered from application deployment workflow"}'
