name: "Docker Image Build Test"

on:
  workflow_dispatch:
  pull_request:

jobs:

  build-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Setup Maven and JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Run tests
      run: mvn test
    
    # Maven build
    - name: Build with Maven
      run: mvn package

   # Build Docker image
    - name: Build Docker image
      run: docker build .
